apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otus
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/Kuber-2025-04OTUS/Neprincessa_repo
  destinations:
    - namespace: homework
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'