apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-templating
  namespace: argocd
spec:
  project: otus
  source:
    repoURL: https://github.com/Kuber-2025-04OTUS/Neprincessa_repo
    path: kubernetes-templating/hw-app
    targetRevision: kubernetes-templating
    helm:
      valueFiles:
        - values.yaml
      values: 'replicas: 2'
  destination:
    server: https://kubernetes.default.svc
    namespace: homeworkhelm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true      