apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
  labels:
    app.kubernetes.io/name: nginx-service
data:
  nginx.conf: |
     events {}
     http {
        server {
                listen 80;
                server_name localhost;

                location / {
                        root /homework;
                        index index.html index.htm;
                }

                location /homework {
                        root /homework;
                        index index.html index.htm;
                }

                location /homework/ {
                        return 301 /homework;
                        }

                location ~ /basic_status  {
                        stub_status ;
                        
                        allow all;
                        
                        }                        
                }             
        }
