apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: nginx-service
data:
 {{- with .Values.configMap.config }}
  nginx.conf:  
        {{- toYaml . | nindent 8 }}
{{- end }}