apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hw-app.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
  {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host | default "homework.otus" }}
    http:
      paths:
      - path: {{ .Values.ingress.path | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "hw-app.fullname" . }}-service
            port:
              number: {{ .Values.service.port }}
