apiVersion: v1
kind: Service
metadata:
  name: {{ include "hw-app.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hw-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-port
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "hw-app.selectorLabels" . | nindent 4 }}