broker:
  replicaCount: 1
  
controller:
  replicaCount: 1

listeners:
  client:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT  

# resources:
#   requests:
#     cpu: "3"
#     memory: "3Gi"
#   limits:
#     cpu: "4"
#     memory: "4Gi"

controller:
  heapOpts: "-Xmx512M -Xms512M"  # Ограничение памяти JVM

# heapOpts: -XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=50

persistence:
  # Disable persistence to prevent volume permission issues in Minikube
  enabled: false